---
- hosts: all
  vars_files:
  - env_variables_ubuntu

  tasks:
  # Creating runtime
  - name: Removing packages
    apt:
      name: "{{ item }}"
      state: absent
    with_items: "{{ container_packages_remove }}"

  - name: Installing required container runtime packages
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items: "{{ container_initial_packages }}"

  - name: Creating container runtime keyrings directory
    file:
      path: /etc/apt/keyrings
      state: directory
      owner: root
      group: root
      mode: '0755'

  - name: Download container runtime repo key
    get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /tmp/docker.gpg
    register: gpgkey

  - name: Adding the container runtime repo key
    shell: cat /tmp/docker.gpg | gpg --dearmor > /etc/apt/keyrings/docker.gpg
    when: gpgkey.changed

  - name: Adding repository details in container runtime repo file
    template:
      src: docker.j2
      dest: /etc/apt/sources.list.d/docker.list

  - name: Updating apt cache
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

  - name: Installing container runtime required packages
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items: "{{ container_runtime_packages }}"

  - name: Adding container runtime config (toml) file
    template:
      src: config.j2
      dest: /etc/containerd/config.toml

  - name: Starting and enabling the required container runtime services
    service:
      name: "{{ item }}"
      state: restarted
      enabled: yes
    with_items: "{{ container_runtime_services }}"

  # Kubernetes configuration
  - name: Creating Kubernetes keyrings directory
    file:
      path: /etc/apt/keyrings
      state: directory
      owner: root
      group: root
      mode: '0755'

  - name: Download Kubernetes Release key and convert to keyring
    shell: |
      curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    args:
      creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

  - name: Adding Kubernetes apt repository
    apt_repository:
      repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /'
      filename: 'kubernetes.list'
      state: present
      update_cache: yes

  - name: Updating apt cache
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

  - name: Installing specific versions of Kubernetes packages
    apt:
      name:
        - kubeadm=1.28.1-1.1
        - kubelet=1.28.1-1.1
        - kubectl=1.28.1-1.1
      state: present
      update_cache: yes
      allow_downgrade: yes

  - name: Starting and enabling the required services
    service:
      name: "{{ item }}"
      state: restarted
      enabled: yes
    with_items: "{{ services }}"

